cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "thoughtbot/formulae"

brew "mas"

mas "Docs for Xcode", id: 688199928

mas "Pages", id: 409201541
mas "Numbers", id: 409203825
mas "Keynote", id: 409183694
mas "iMovie", id: 408981434
mas "Microsoft Remote Desktop", id: 1295203466
mas "Pocket", id: 568494494
mas "Save to Pocket", id: 1477385213
mas "feedly", id: 865500966
mas "GarageBand", id: 682658836
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835

cask "aerial"
cask "alfred"
cask "android-studio"
cask "anki"
cask "authy"
cask "blu-ray-player"
cask "clipy"
cask "dbeaver-community"
cask "docker"
cask "emacs"
cask "evernote"
cask "fanny"
cask "firefox"
cask "genymotion"
cask "gimp"
cask "google-chrome"
cask "google-cloud-sdk"
cask "hammerspoon"
cask "iterm2"
cask "java11"
cask "keepassxc"
cask "sequel-pro"
cask "skype"
cask "slack"
cask "spotify"
cask "suspicious-package"
cask "the-unarchiver"
cask "transmission"
cask "virtualbox"
cask "vlc"
cask "vnc-viewer"
cask "zoomus"

brew "autoenv"
brew "bash-completion"
brew "brew-cask-completion"
brew "coreutils"
brew "dialog"
brew "docker-compose"
brew "docker-machine"
brew "faac"
brew "ffmpeg"
brew "findutils"
brew "git"
brew "git-flow-avh"
brew "gnu-which"
brew "highlight"
brew "imagemagick"
brew "ispell"
brew "jenv"
brew "kubernetes-cli"
brew "libdvdcss"
brew "libvo-aacenc"
brew "mas"
brew "md5sha1sum"
brew "nmap"
brew "node"
brew "noti"
brew "openjdk@11""
brew "openssh"
brew "pgcli"
brew "postgresql"
brew "prettyping"
brew "pv"
brew "pyenv-virtualenv"
brew "python"
brew "rbenv-default-gems"
brew "rsync"
brew "sphinx-doc"
brew "ssh-copy-id"
brew "subversion"
brew "terminal-notifier"
brew "texi2html"
brew "the_silver_searcher"
brew "wget"
brew "yarn"
brew "yasm"
brew "youtube-dl"
brew "thoughtbot/formulae/rcm"
